[package]

name = "hlua"
version = "0.1.2"
authors = [ "pierre.krieger1708@gmail.com" ]
description = "Zero-cost high-level wrapper for Lua"
repository = "https://github.com/tomaka/hlua"
documentation = "http://tomaka.github.io/hlua/hlua/index.html"
license = "MIT"

[dependencies]
libc = "*"

[dependencies.lua52-sys]
version = "*"
path = "../lua52-sys"
